/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        'primary': '#04142c',
        'on-tertiary-container': '#91908a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'primary-fixed-dim': '#b8c7e7',
        'primary-container': '#1a2942',
        'on-error-container': '#93000a',
        'ink-hover': '#243557',
        'surface-variant': '#e6e2de',
        'on-secondary-fixed': '#0c1d29',
        'outline-variant': '#c5c6ce',
        'surface-container-lowest': '#ffffff',
        'error': '#ba1a1a',
        'on-background': '#1c1b19',
        'text-muted': '#6B6761',
        'inverse-surface': '#32302e',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'secondary-fixed-dim': '#b7c9d9',
        'surface-bright': '#fdf8f5',
        'tertiary-fixed-dim': '#c9c6c0',
        'steel': '#7A8B9A',
        'on-secondary-container': '#546573',
        'on-surface-variant': '#44474d',
        'border-subtle': '#E0DDD8',
        'on-secondary-fixed-variant': '#384956',
        'on-primary-container': '#8290ae',
        'surface-container-low': '#f7f3ef',
        'surface-container-high': '#ece7e4',
        'outline': '#75777e',
        'secondary-fixed': '#d3e5f5',
        'on-tertiary-fixed': '#1c1c18',
        'on-primary-fixed-variant': '#384762',
        'surface-container-highest': '#e6e2de',
        'surface-dim': '#ddd9d6',
        'background': '#fdf8f5',
        'surface-tint': '#505f7a',
        'warm-white': '#F5F3F0',
        'secondary': '#50606e',
        'tertiary-container': '#292925',
        'surface': '#fdf8f5',
        'on-primary-fixed': '#0b1b34',
        'inverse-primary': '#b8c7e7',
        'tertiary': '#151511',
        'on-tertiary-fixed-variant': '#474742',
        'primary-fixed': '#d6e3ff',
        'paper': '#F2EFE8',
        'tertiary-fixed': '#e5e2db',
        'on-surface': '#1c1b19',
        'inverse-on-surface': '#f5f0ec',
        'ink-pressed': '#0F1B2E',
        'secondary-container': '#d0e2f2',
        'ink-blue': '#1A2942',
        'surface-container': '#f2ede9',
        'on-tertiary': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
        none: '0px',
      },
      spacing: {
        unit: '6px',
        sm: '12px',
        'reading-width': '680px',
        'margin-mobile': '24px',
        xxl: '96px',
        xxxl: '128px',
        xl: '64px',
        'max-width': '1200px',
        md: '24px',
        lg: '48px',
        gutter: '24px',
        xs: '6px',
      },
      fontFamily: {
        'display-lg-mobile': ['Playfair Display', 'serif'],
        'label-caps': ['Montserrat', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-sm': ['Playfair Display', 'serif'],
        tagline: ['Playfair Display', 'serif'],
        metadata: ['JetBrains Mono', 'monospace'],
        'headline-md': ['Playfair Display', 'serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-sm': ['Montserrat', 'sans-serif'],
        'display-lg': ['Playfair Display', 'serif'],
      },
      fontSize: {
        'display-lg-mobile': ['48px', { lineHeight: '1.2', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.12em', fontWeight: '600' }],
        'body-lg': ['19px', { lineHeight: '1.75', fontWeight: '400' }],
        'headline-sm': ['26px', { lineHeight: '1.3', fontWeight: '600' }],
        tagline: ['22px', { lineHeight: '1.5', fontWeight: '400' }],
        metadata: ['12px', { lineHeight: '1.4', fontWeight: '400' }],
        'headline-md': ['44px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-md': ['17px', { lineHeight: '1.65', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '1', letterSpacing: '0.08em', fontWeight: '600' }],
        'display-lg': ['80px', { lineHeight: '1.1', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
